"""Job & session retention endpoints.

Exposes read, delete, bulk-cleanup, and download operations over the
retention-aware jobs created by ``/api/packs/build-from-upload``. All routes are
under ``/api/*`` and therefore covered by API-key auth.
"""

from __future__ import annotations

from fastapi import APIRouter, HTTPException, Query
from fastapi.responses import FileResponse

from app.core import jobs_store, pack_io, storage
from app.core.pack_io import UnsafePathError
from app.models.job_schema import (
    CleanupSummary,
    JobResponse,
    job_to_response,
)

router = APIRouter(prefix="/api/jobs", tags=["jobs"])


@router.get(
    "/{job_id}",
    response_model=JobResponse,
    operation_id="getJob",
    summary="Get job metadata",
    description=(
        "Return retention metadata for a job: status, retention_mode, expiry, "
        "whether raw uploads/working files were deleted, whether the pack is "
        "persisted, and the download_url. Server paths are hidden unless "
        "debug=true."
    ),
)
def get_job(job_id: str, debug: bool = Query(default=False)) -> JobResponse:
    """Return metadata for a single job."""
    job = jobs_store.load_job(job_id)
    if job is None:
        raise HTTPException(status_code=404, detail="Job not found.")
    return job_to_response(job, debug=debug)


@router.delete(
    "/{job_id}",
    response_model=JobResponse,
    operation_id="deleteJob",
    summary="Delete a job and its temporary data",
    description=(
        "Force-clean a job: delete its raw upload and working files, and (for "
        "session / process_and_return modes) its temporary pack. server_vault "
        "packs are preserved. Returns the updated job metadata."
    ),
)
def delete_job(job_id: str, debug: bool = Query(default=False)) -> JobResponse:
    """Force-clean a single job and return its updated metadata."""
    if jobs_store.load_job(job_id) is None:
        raise HTTPException(status_code=404, detail="Job not found.")
    job = jobs_store.cleanup_job(job_id)
    if job is None:  # pragma: no cover - race guard
        raise HTTPException(status_code=404, detail="Job not found.")
    return job_to_response(job, debug=debug)


@router.post(
    "/cleanup",
    response_model=CleanupSummary,
    operation_id="cleanupJobs",
    summary="Clean up expired temporary jobs",
    description=(
        "Delete temporary packs and working files for jobs whose TTL has "
        "expired, plus staged uploads that were never consumed. server_vault "
        "packs are never removed. Returns counts of jobs cleaned, packs, and "
        "uploads deleted."
    ),
)
def cleanup_jobs() -> CleanupSummary:
    """Delete expired temporary packs, working files, and staged uploads."""
    summary = jobs_store.cleanup_expired_temp_jobs()
    summary["uploads_deleted"] = storage.cleanup_expired_uploads()
    return CleanupSummary(**summary)


@router.get(
    "/{job_id}/download",
    operation_id="getJobDownload",
    summary="Download a generated pack",
    description=(
        "Stream the Safe Memory Pack file generated by a job. Available while "
        "the pack still exists (temporary packs are removed after their TTL)."
    ),
)
def get_job_download(job_id: str):
    """Stream the generated pack file for a job."""
    job = jobs_store.load_job(job_id)
    if job is None:
        raise HTTPException(status_code=404, detail="Job not found.")
    if not job.pack_path:
        raise HTTPException(status_code=404, detail="No pack available for this job.")
    try:
        path = pack_io.ensure_safe_path(job.pack_path)
    except UnsafePathError:
        raise HTTPException(status_code=400, detail="Unsafe pack path rejected.")
    if not path.exists():
        raise HTTPException(
            status_code=404,
            detail="Pack is no longer available (it may have expired).",
        )
    return FileResponse(
        path=str(path),
        media_type="application/json",
        filename=f"{job.pack_id}.smp.json",
    )
